name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update apt cache
        run: |
          sudo apt-get update -qq \
            -o Dir::Etc::sourcelist="sources.list" \
            -o Dir::Etc::sourceparts="-" \
            -o APT::Get::List-Cleanup="0"

      - name: Install build dependencies
        run: sudo apt-get install -y gnat gprbuild

      - name: Build
        run: make

      - name: Test
        run: make test
